TERMS_TEXT = (
    "📄 <b>Foydalanish shartlari</b>\n\n"
    "TeleMind AI Botdan foydalanish orqali siz quyidagi shartlarga rozilik bildirasiz.\n\n"
    "<b>1. Bot vazifasi</b>\n"
    "Bot AI suhbat, matn yaratish, tarjima, xulosa, personajlar, Telegram account ulash, "
    "AI yordamchi, guruh funksiyalari, premium tariflar, promokod va referal imkoniyatlarini taqdim etadi.\n\n"
    "<b>2. AI javoblari</b>\n"
    "AI javoblari doim ham mutlaq to‘g‘ri bo‘lmasligi mumkin. Muhim qarorlar, huquqiy, tibbiy, moliyaviy "
    "yoki xavfsizlikka oid masalalarda javoblarni mustaqil tekshiring.\n\n"
    "<b>3. Foydalanuvchi mas’uliyati</b>\n"
    "Siz botdan qonuniy, odobli va xavfsiz maqsadlarda foydalanishingiz kerak. Spam, firibgarlik, haqorat, "
    "zararli kontent, maxfiy ma’lumotlarni ruxsatsiz tarqatish yoki Telegram qoidalarini buzish taqiqlanadi.\n\n"
    "<b>4. Telegram account ulash</b>\n"
    "Account ulash ixtiyoriy. Ulangan account orqali AI yordamchi shaxsiy xabarlarga javob berishi, tanlangan "
    "guruhlar uchun reply/metka javoblari va timer xabarlarini yuborishi mumkin. Siz istalgan vaqtda accountni uzishingiz mumkin.\n\n"
    "<b>5. Premium va to‘lovlar</b>\n"
    "Premium tariflar Telegram Stars orqali sotib olinadi. To‘lov muvaffaqiyatli yakunlangach tarif avtomatik faollashadi. "
    "Tarif muddati, limitlar va narxlar bot ichida ko‘rsatiladi.\n\n"
    "<b>6. Limitlar va bloklash</b>\n"
    "Botda kunlik AI limitlar, bonus kreditlar va promokod limitlari mavjud. Qoidalarni buzgan foydalanuvchi "
    "admin tomonidan bloklanishi yoki ayrim funksiyalardan cheklanishi mumkin.\n\n"
    "<b>7. O‘zgarishlar</b>\n"
    "Bot funksiyalari, tariflar, limitlar va shartlar vaqt o‘tishi bilan yangilanishi mumkin. Yangilangan shartlar botda e’lon qilinadi.\n\n"
    "Botdan foydalanishni davom ettirish yangilangan shartlarga rozilik sifatida qabul qilinadi."
)


PRIVACY_TEXT = (
    "🔐 <b>Maxfiylik siyosati</b>\n\n"
    "Ushbu siyosat TeleMind AI Bot qanday ma’lumotlarni ishlatishini tushuntiradi.\n\n"
    "<b>1. Saqlanishi mumkin bo‘lgan ma’lumotlar</b>\n"
    "Bot Telegram ID, username, ism, til kodi, tarif, limitlar, bonus kreditlar, tanlangan personaj, prompt, "
    "to‘lov holati, promokod/referal ma’lumotlari va bot bilan yozishmalar tarixini saqlashi mumkin.\n\n"
    "<b>2. AI xabarlar</b>\n"
    "AI javob berishi uchun user yuborgan matn, so‘rov konteksti va tanlangan sozlamalar AI providerga yuborilishi mumkin. "
    "Maxfiy parol, karta, token yoki shaxsiy sirlarni AI chatga yubormaslik tavsiya qilinadi.\n\n"
    "<b>3. Telegram account session</b>\n"
    "Account ulansa, Telethon session shifrlangan holda saqlanadi. Login kodi va 2FA parol saqlanmaydi. "
    "Account uzilganda session ma’lumotlari o‘chiriladi.\n\n"
    "<b>4. Guruh va auto-reply</b>\n"
    "Tanlangan guruhlarda reply/metka bo‘lgan xabarlar AI javob tayyorlashi uchun qayta ishlanishi mumkin. "
    "Shaxsiy xabarlarga AI yordamchi yoqilgan bo‘lsa, kiruvchi xabarlar javob tayyorlash uchun ishlatiladi.\n\n"
    "<b>5. To‘lov ma’lumotlari</b>\n"
    "Telegram Stars to‘lovlarida bot to‘lov statusi, tarif, miqdor, invoice payload va Telegram charge ID kabi texnik ma’lumotlarni saqlaydi. "
    "Karta ma’lumotlari botda saqlanmaydi.\n\n"
    "<b>6. Ma’lumotlardan foydalanish</b>\n"
    "Ma’lumotlar botni ishlatish, limitlarni hisoblash, premiumni faollashtirish, xavfsizlik, admin boshqaruvi, "
    "AI javoblar va xizmat sifatini yaxshilash uchun ishlatiladi.\n\n"
    "<b>7. Ma’lumotlarni o‘chirish</b>\n"
    "Foydalanuvchi accountni uzishi, promptni tozalashi yoki admin orqali ma’lumotlarini o‘chirishni so‘rashi mumkin. "
    "Texnik va to‘lov loglari xavfsizlik yoki hisob-kitob uchun ma’lum muddat saqlanishi mumkin.\n\n"
    "<b>8. Xavfsizlik</b>\n"
    "Bot sessionlarni shifrlash, admin tekshiruvi, limit nazorati va bloklash mexanizmlaridan foydalanadi. "
    "Shunga qaramay, internet orqali yuborilgan har qanday ma’lumotda nol xavf kafolatlanmaydi."
)


LEGAL_CONSENT_TEXT = (
    "📄 <b>Shartlar va maxfiylik</b>\n\n"
    "Botdan foydalanishni boshlashdan oldin foydalanish shartlari va maxfiylik siyosati bilan tanishib chiqing.\n\n"
    "Rozilik berish orqali siz:\n"
    "• bot AI javoblari doim tekshirilishi kerakligini;\n"
    "• Telegram account ulash ixtiyoriy ekanini;\n"
    "• AI chat va yordamchi funksiyalari uchun xabarlar qayta ishlanishini;\n"
    "• premium, promokod, limit va admin qoidalariga roziligingizni tasdiqlaysiz.\n\n"
    "Davom etish uchun <b>✅ Roziman</b> tugmasini bosing."
)
